services:
  # Backend Web Service (Spring Boot Docker)
  - type: web
    name: ecommerce_backend
    env: docker
    plan: free
    region: frankfurt
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: JWT_SECRET
        value: 4512908f-2871-460d-85fa-7a8e7e10c7a5-very-secure-key-that-is-long-enough

  # Frontend Static Site (React/Vite)
  - type: web
    name: ecommerce_frontend
    env: static
    rootDir: frontend
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://ecommerce-backend-sex1.onrender.com/backend/api
