spring.application.name=ecommerce-backend

# Server Configuration
server.servlet.context-path=${SERVER_CONTEXT_PATH:/backend}
server.port=${PORT:8080}

# Database Configuration (Network Deployment)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://10.180.186.74:3306/ecommerce_db?allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Security Configuration
spring.web.cors.allowed-origins=*
